version: "3"
services:
  shop_backstage_test:
    build:
      context: ./
      args:                                                                     
        - BUILD_API_NAME=test
        - BUILD_DIST_NAME=test
    image: shop_backstage_test:v1
    restart: unless-stopped
    container_name: shop_backstage_test
    ports:
      - 8010:80
  shop_backstage_webs:
    build:
      context: ./
      args:                                                                     
        - BUILD_API_NAME=webs
        - BUILD_DIST_NAME=webs
    image: shop_backstage_webs:v1
    restart: unless-stopped
    container_name: shop_backstage_webs
    ports:
      - 8030:80