version: "3"
services:
  shop_backstage_local:
    build:
      context: ./
      args:                                                                     
        - BUILD_API_NAME=local
        - BUILD_DIST_NAME=local
    image: shop_backstage_local:v1
    restart: unless-stopped
    container_name: shop_backstage_local
    ports:
      - 10978:80